### Primero se importan las bibliotecas necesarias

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os
import time
import psutil
from collections import defaultdict
import seaborn as sns
import optuna
from concurrent.futures import ThreadPoolExecutor
# Especiales de RecSys
import surprise
from surprise import accuracy
from surprise import SVD
from surprise import SVDpp
from surprise.model_selection import PredefinedKFold
from surprise.model_selection import cross_validate
import implicit
import scipy.sparse as sparse

### Funciones utiles

In [2]:
def costo_computacional(algoritmo, trainset, imprimir=True):
    proceso = psutil.Process()
    inicio_tiempo = time.time()
    inicio_cpu = proceso.cpu_percent(interval=None)
    inicio_memoria = proceso.memory_info().rss

    algoritmo.fit(trainset)

    fin_tiempo = time.time()
    fin_cpu = proceso.cpu_percent(interval=None)
    fin_memoria = proceso.memory_info().rss

    tiempo = fin_tiempo - inicio_tiempo
    cpu = fin_cpu - inicio_cpu
    memoria = (fin_memoria - inicio_memoria) / (1024 * 1024)

    if imprimir:
        print(f"Tiempo entrenamiento: {tiempo:.2f} segundos")
        print(f"Uso de CPU: {cpu:.2f}%")
        print(f"Uso de memoria: {memoria:.2f} MB")
    return tiempo, cpu, memoria

def get_top_n(predictions, n=10):
    """Devuelve las N-mejores recomendaciones para cada usuario de un set de predicción.

    Args:
        predictions(lista de objetos Prediction): La lista de predicción obtenida del método test.
        n(int): El número de recomendaciónes por usuario

    Returns:
    Un diccionario donde las llaves son ids de usuario y los valores son listas de tuplas:
        [(item id, rating estimation), ...] de tamaño n.
    """

    # First map the predictions to each user.
    top_n = defaultdict(list)
    for uid, iid, true_r, est, _ in predictions:
        top_n[uid].append((iid, est))

    # Then sort the predictions for each user and retrieve the k highest ones.
    for uid, user_ratings in top_n.items():
        user_ratings.sort(key=lambda x: x[1], reverse=True)
        top_n[uid] = user_ratings[:n]

    return top_n

# Definicion de métricas (No editar)

def precision_at_k(r, k):
    assert 1 <= k <= r.size
    return (np.asarray(r)[:k]).mean()

def average_precision_at_k(r, k):
    r = np.asarray(r)
    n_rel = r.sum() # Número de items relevantes
    if n_rel == 0:
        return 0.
    vectorized_precision = np.vectorize(lambda i: precision_at_k(r, i))
    indices = np.arange(1, len(r) + 1)
    precisions = vectorized_precision(indices) # Precision@k por cada posición del ranking
    score = np.sum(precisions * r)
    return score / min(k, n_rel)

def dcg_at_k(r, k):
    r = np.asarray(r)[:k]
    if r.size:
        return np.sum(np.subtract(np.power(2, r), 1) / np.log2(np.arange(2, r.size + 2)))
    return 0.

def ndcg_at_k(r, k):
    idcg = dcg_at_k(sorted(r, reverse=True), k)

    if not idcg:
        return 0.
    return dcg_at_k(r, k) / idcg

### Datos a utilizar

In [3]:
train_data = pd.read_csv("datos/train.csv")
validation_data = pd.read_csv("datos/validation.csv")
vg_data = pd.read_csv("datos/videogames_metadata.csv")

In [4]:
display(train_data.head(1))
display(validation_data.head(1))
display(vg_data.head(1))

,rating,review_title,text,user_id,timestamp,item_title,item_id
0,5.0,One of my favorites !,Great game in the series !,149157,2017-11-13 10:53:02.745,Medal of Honor - PC,4946

,rating,review_title,text,timestamp,item_title,item_id,user_id
0,5.0,Five Stars,yay,2015-03-16 16:15:22.000,WWF Smackdown 2: Know Your Role,23386,238159

,title,average_rating,rating_number,features,description,price,store,categories,item_id,image
0,Dash 8-300 Professional Add-On,5.0,1,"""Features Dash 8-300 and 8-Q300 (Q rollout liv...",The Dash 8-300 Professional Add-On lets you pi...,NaN,Aerosoft,"PC, Games",118568,https://m.media-amazon.com/images/I/21DVWE41A0...

### Necesario para Random, Uknn, Iknn y FunkSVD

In [ ]:
# La lectura de datos sirve tanto para item-based como para funkSVD al usar Surprise
reader = surprise.Reader(rating_scale=(1,5))
trainset = surprise.Dataset.load_from_df(train_data[["user_id", "item_id", "rating"]], reader).build_full_trainset()
a_testset = trainset.build_anti_testset()
testset = a_testset 
# Este test set tiene 97,875,651 lo cual es demasiado grande para evaluar
# Por lo mismo lo vamos a reducir a solo los items rankeados por los vecinos de cada usuario

### 1. Random

In [5]:
# Creamos un database de predicciones aleatorias que puede ser utilizado por get_top_n
random_pred = validation_data[["user_id", "item_id", "rating"]].copy()
random_pred["estimado"] = np.random.uniform(1, 5, size=len(random_pred))

# Se convierte en una lista de tuplas en el formato (uid, iid, true_r, est, _)
predictions_random = []
for _, row in random_pred.iterrows():
    predictions_random.append((int(row['user_id']), int(row['item_id']), float(row['rating']), float(row['estimado']), None))

# Obtener las mejores N recomendaciones
top_n_random = get_top_n(predictions_random, n=10)

### 2. User-based collaborative filtering

In [ ]:
# Parte especifica de entrenamiento del algoritmo
myUserKnn = surprise.KNNBasic(k=7, sim_options={'name': 'pearson', 'user_based': True})
tiempo, cpu, memoria =costo_computacional(myUserKnn, trainset, True)
predictions_uknn = myUserKnn.test(testset)
# Obtener las mejores N recomendaciones
top_n_uknn = get_top_n(predictions_uknn, n=10)
print("\n Top 10 listo\n")
top_n_uknn

### 2. Item-based collaborative filtering

In [ ]:
# Parte especifica de entrenamiento del algoritmo
myItemKnn = surprise.KNNBasic(k=7, sim_options={'name': 'pearson', 'user_based': False})
tiempo, cpu, memoria =costo_computacional(myItemKnn, trainset, False)
predictions_iknn = myItemKnn.test(testset)
# Obtener las mejores N recomendaciones
top_n_iknn = get_top_n(predictions_iknn, n=10)

### 3. FunkSVD

In [ ]:
# Parte especifica de entrenamiento del algoritmo
funksvd = SVD(n_factors = 100, n_epochs = 20, lr_all = 0.005, reg_all = 0.02)
tiempo, cpu, memoria =costo_computacional(funksvd, trainset, imprimir = False)
predictions_funksvd = funksvd.test(testset)

# Obtener las mejores N recomendaciones
top_n_funksvd = get_top_n(predictions_funksvd, n=10)

### Preprocesamiento de los datos a formato sparse y funciones para ALS y BPR

In [ ]:
df_test = validation_data[["user_id", "item_id", "rating", "timestamp"]].copy()

# rating >= 3 es relevante (1) y rating menor a 3 es no relevante (0)
df_test.rating = [1 if x >=3 else 0 for x in df_test.rating ]

df_test.sort_values(by=["user_id", "timestamp"], inplace=True)

user_items_test = {}

for row in df_test.itertuples():
    if row[1] not in user_items_test:
        user_items_test[row[1]] = []

    user_items_test[row[1]].append(row[2])

In [ ]:
df_train = train_data[["user_id", "item_id"]].copy()

user_items = {}
itemset = set()

for row in df_train.itertuples():
    if row[1] not in user_items:
        user_items[row[1]] = []

    user_items[row[1]].append(row[2])
    itemset.add(row[2])

itemset = np.sort(list(itemset))

sparse_matrix = np.zeros((len(user_items), len(itemset)))

for i, items in enumerate(user_items.values()):
    sparse_matrix[i] = np.isin(itemset, items, assume_unique=True).astype(int)

matrix = sparse.csr_matrix(sparse_matrix.T)

user_ids = {key: i for i, key in enumerate(user_items.keys())}
user_item_matrix = matrix.T.tocsr()

# Para traducir los id back and forth
# Forward mappings: original ID → matrix index
user2id = {user: i for i, user in enumerate(user_items.keys())}
item2id = {item: i for i, item in enumerate(itemset)}

# Reverse mappings: matrix index → original ID
id2user = {i: user for user, i in user2id.items()}
id2item = {i: item for item, i in item2id.items()}

In [ ]:
# Funciones
def evaluate_model(model, n):
  mean_ap = 0. # o MAP
  mean_ndcg = 0.
  for u in user_items_test.keys():
    u_original = u
    u_matriz = user2id[u]
    rec = model.recommend(u_matriz, user_item_matrix[u_matriz], n)[0]
    rec_original = [id2item[i] for i in rec]
    rel_vector = np.isin(rec_original, user_items_test[u_original], assume_unique=True).astype(int)
    mean_ap += average_precision_at_k(rel_vector, n)
    mean_ndcg += ndcg_at_k(rel_vector, n)

  mean_ap /= len(user_items_test)
  mean_ndcg /= len(user_items_test)

  return mean_ap, mean_ndcg

def show_recommendations(model, user, n):
  user_matriz = user2id[user]
  recommendations = model.recommend(userid=user_matriz, user_items=user_item_matrix[user_matriz], N=n)[0]
  recommendations_original = [id2item[i] for i in recommendations]
  return vg_data.loc[recommendations_original]['title']

def show_similar_movies(model, item, n=10):
  item_matriz = item2id[item]
  sim_items = model.similar_items(item_matriz, n)[0]
  sim_items_original = [id2item[i] for i in sim_items]
  return vg_data.loc[sim_items_original]['title']

### 4. ALS

In [ ]:
factors = 117
iterations = 14
model_als = implicit.als.AlternatingLeastSquares(factors=factors, iterations=iterations, use_gpu=False)
tiempo, cpu, memoria =costo_computacional(model_als, user_item_matrix, imprimir = True)
# show_recommendations(model_als, user=59, n=10)
# show_similar_movies(model_als, item=171, n=10)
maprec, ndcg = evaluate_model(model_als, n=10)
print('map: {}\nndcg: {}'.format(maprec, ndcg))

# Best is trial 5 with value: 0.056847841963295974. {'factors': 117, 'iterations': 14}

  0%|          | 0/14 [00:00<?, ?it/s]

Tiempo entrenamiento: 16.45 segundos
Uso de CPU: 955.10%
Uso de memoria: 2.33 MB
map: 0.055541966299190206
ndcg: 0.07575406896934898

### 5. BPR

In [ ]:
factors = 67
iterations = 300
model_bpr = implicit.bpr.BayesianPersonalizedRanking(factors=factors, iterations=iterations, use_gpu=False)
tiempo, cpu, memoria =costo_computacional(model_bpr, user_item_matrix, imprimir = True)
# show_recommendations(model_bpr, user=77, n=10)
# show_similar_movies(model_bpr, item=171, n=10)
maprec, ndcg = evaluate_model(model_bpr, n=10)
print('map: {}\nndcg: {}'.format(maprec, ndcg))

  0%|          | 0/300 [00:00<?, ?it/s]

Tiempo entrenamiento: 4.68 segundos
Uso de CPU: 100.20%
Uso de memoria: 5.97 MB
map: 0.04448369016222467
ndcg: 0.060920600628166933

In [ ]:
def objective(trial):
    factors = trial.suggest_int("factors", 50, 300)
    iterations = trial.suggest_int("iterations", 10, 40)
    model = implicit.als.AlternatingLeastSquares(factors=factors, iterations=iterations)
    model.fit(user_item_matrix)
    map_val, ndcg_val = evaluate_model(model, n=10)
    return map_val  # maximize MAP

study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=50)
print(study.best_params)

### 6. Factorization Machines