### Primero se importan las bibliotecas necesarias

In [31]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os
import time
import psutil
from collections import defaultdict
import seaborn as sns
# Especiales de RecSys
import surprise
from surprise import accuracy
from surprise import SVD
from surprise import SVDpp
from surprise.model_selection import PredefinedKFold
from surprise.model_selection import cross_validate
import implicit
import scipy.sparse as sparse

### Funciones utiles

In [32]:
def costo_computacional(algoritmo, trainset, imprimir=True):
    proceso = psutil.Process()
    inicio_tiempo = time.time()
    inicio_cpu = proceso.cpu_percent(interval=None)
    inicio_memoria = proceso.memory_info().rss

    algoritmo.fit(trainset)

    fin_tiempo = time.time()
    fin_cpu = proceso.cpu_percent(interval=None)
    fin_memoria = proceso.memory_info().rss

    tiempo = fin_tiempo - inicio_tiempo
    cpu = fin_cpu - inicio_cpu
    memoria = (fin_memoria - inicio_memoria) / (1024 * 1024)

    if imprimir:
        print(f"Tiempo entrenamiento: {tiempo:.2f} segundos")
        print(f"Uso de CPU: {cpu:.2f}%")
        print(f"Uso de memoria: {memoria:.2f} MB")
    return tiempo, cpu, memoria

def get_top_n(predictions, n=10):
    """Devuelve las N-mejores recomendaciones para cada usuario de un set de predicción.

    Args:
        predictions(lista de objetos Prediction): La lista de predicción obtenida del método test.
        n(int): El número de recomendaciónes por usuario

    Returns:
    Un diccionario donde las llaves son ids de usuario y los valores son listas de tuplas:
        [(item id, rating estimation), ...] de tamaño n.
    """

    # First map the predictions to each user.
    top_n = defaultdict(list)
    for uid, iid, true_r, est, _ in predictions:
        top_n[uid].append((iid, est))

    # Then sort the predictions for each user and retrieve the k highest ones.
    for uid, user_ratings in top_n.items():
        user_ratings.sort(key=lambda x: x[1], reverse=True)
        top_n[uid] = user_ratings[:n]

    return top_n

# Definicion de métricas (No editar)

def precision_at_k(r, k):
    assert 1 <= k <= r.size
    return (np.asarray(r)[:k]).mean()

def average_precision_at_k(r, k):
    r = np.asarray(r)
    n_rel = r.sum() # Número de items relevantes
    if n_rel == 0:
        return 0.
    vectorized_precision = np.vectorize(lambda i: precision_at_k(r, i))
    indices = np.arange(1, len(r) + 1)
    precisions = vectorized_precision(indices) # Precision@k por cada posición del ranking
    score = np.sum(precisions * r)
    return score / min(k, n_rel)

def dcg_at_k(r, k):
    r = np.asarray(r)[:k]
    if r.size:
        return np.sum(np.subtract(np.power(2, r), 1) / np.log2(np.arange(2, r.size + 2)))
    return 0.

def ndcg_at_k(r, k):
    idcg = dcg_at_k(sorted(r, reverse=True), k)

    if not idcg:
        return 0.
    return dcg_at_k(r, k) / idcg

### Datos a utilizar

In [33]:
train_data = pd.read_csv("datos/train.csv")
validation_data = pd.read_csv("datos/validation.csv")
vg_data = pd.read_csv("datos/videogames_metadata.csv")

In [34]:
validation_data.head()

,rating,review_title,text,timestamp,item_title,item_id,user_id
0,5.0,Five Stars,yay,2015-03-16 16:15:22.000,WWF Smackdown 2: Know Your Role,23386,238159
1,5.0,Fantastic Reprise of a Classic,Shogun: Total War was the title that marked th...,2011-05-11 14:40:55.000,Total War: Shogun 2 -The Blood Pack DLC [Onlin...,11444,9040
2,3.0,Staircase movement action sucks,Remember block graphics? Like when Fry become...,2009-04-02 14:38:37.000,Final Fantasy Crystal Chronicles: Echoes of Ti...,14619,502328
3,3.0,Three Stars,nice!,2015-06-08 16:52:08.000,Age of Empires III: The Asian Dynasties Expans...,11644,210635
4,5.0,Just what I needed!,It came on time and in perfect condition. I've...,2013-01-18 08:21:26.000,Xbox 360 Data Transfer Cable,17020,1665901

### 1. Random

In [35]:
# Creamos un database de predicciones aleatorias que puede ser utilizado por get_top_n
random_pred = validation_data[["user_id", "item_id", "rating"]].copy()
random_pred["estimado"] = np.random.uniform(1, 5, size=len(random_pred))

# Se convierte en una lista de tuplas en el formato (uid, iid, true_r, est, _)
predictions_random = []
for _, row in random_pred.iterrows():
    predictions_random.append((int(row['user_id']), int(row['item_id']), float(row['rating']), float(row['estimado']), None))

# Obtener las mejores N recomendaciones
top_n_random = get_top_n(predictions_random, n=10)

### 2. Item-based collaborative filtering

In [36]:
# La lectura de datos sirve tanto para item-based como para funkSVD al usar Surprise
reader = surprise.Reader(rating_scale=(1,5))
trainset = surprise.Dataset.load_from_df(train_data[["user_id", "item_id", "rating"]], reader).build_full_trainset()
testset = list(zip(validation_data["user_id"], validation_data["item_id"], validation_data["rating"]))

# Parte especifica de entrenamiento del algoritmo
myItemKnn = surprise.KNNBasic(k=7, sim_options={'name': 'pearson', 'user_based': False})
tiempo, cpu, memoria =costo_computacional(myItemKnn, trainset, False)
predictions_iknn = myItemKnn.test(testset)

# Obtener las mejores N recomendaciones
top_n_iknn = get_top_n(predictions_iknn, n=10)

Computing the pearson similarity matrix...
Done computing similarity matrix.

### 3. FunkSVD

In [37]:
# Parte especifica de entrenamiento del algoritmo
funksvd = SVD(n_factors = 100, n_epochs = 20, lr_all = 0.005, reg_all = 0.02)
tiempo, cpu, memoria =costo_computacional(funksvd, trainset, False)
predictions_funksvd = funksvd.test(testset)

# Obtener las mejores N recomendaciones
top_n_funksvd = get_top_n(predictions_funksvd, n=10)

### Preprocesamiento de los datos a formato sparse y funciones para ALS y BPR

In [44]:
df_test = validation_data[["user_id", "item_id", "rating", "timestamp"]].copy()

# rating >= 3 es relevante (1) y rating menor a 3 es no relevante (0)
df_test.rating = [1 if x >=3 else 0 for x in df_test.rating ]

user_items_test = {}

for row in df_test.itertuples():
    if row[1] not in user_items_test:
        user_items_test[row[1]] = []

    user_items_test[row[1]].append(row[2])

df_test.head()

   user_id  item_id  rating                timestamp
0   238159    23386       1  2015-03-16 16:15:22.000
1     9040    11444       1  2011-05-11 14:40:55.000
2   502328    14619       1  2009-04-02 14:38:37.000
3   210635    11644       1  2015-06-08 16:52:08.000
4  1665901    17020       1  2013-01-18 08:21:26.000

In [39]:
# Preprocesamiento a formato sparse
user_items = {}
itemset = set()

train_formato_sparse = train_data[["user_id", "item_id"]].copy()

for row in train_formato_sparse.itertuples():
    if row[1] not in user_items:
        user_items[row[1]] = []

    user_items[row[1]].append(row[2])
    itemset.add(row[2])

itemset = np.sort(list(itemset))

sparse_matrix = np.zeros((len(user_items), len(itemset)))

for i, items in enumerate(user_items.values()):
    sparse_matrix[i] = np.isin(itemset, items, assume_unique=True).astype(int)

matrix = sparse.csr_matrix(sparse_matrix.T)

user_ids = {key: i for i, key in enumerate(user_items.keys())}
user_item_matrix = matrix.T.tocsr()

In [40]:
# Funciones
def evaluate_model(model, n):
  mean_ap = 0. # o MAP
  mean_ndcg = 0.
  for u in user_items_test.keys():
    rec = model.recommend(u, user_item_matrix[u], n)[0]
    rel_vector = np.isin(user_items_test[u], rec, assume_unique=True).astype(int)
    mean_ap += average_precision_at_k(rel_vector, n)
    mean_ndcg += ndcg_at_k(rel_vector, n)

  mean_ap /= len(user_items_test)
  mean_ndcg /= len(user_items_test)

  return mean_ap, mean_ndcg

def show_recommendations(model, user, n):
  recommendations = model.recommend(userid=user, user_items=user_item_matrix[user], N=n)[0]
  return vg_data.loc[recommendations]['title']

def show_similar_movies(model, item, n=10):
  sim_items = model.similar_items(item, n)[0]
  return vg_data.loc[sim_items]['title']

### 4. ALS

In [41]:
factors = 100
iterations = 15
model_als = implicit.als.AlternatingLeastSquares(factors=factors, iterations=iterations, use_gpu=False)
model_als.fit(user_item_matrix)
maprec, ndcg = evaluate_model(model_als, n=10)

  0%|          | 0/15 [00:00<?, ?it/s]

IndexError: row index (238159) out of range

### 5. BPR

### 6. Factorization Machines