### Primero se importan las bibliotecas necesarias

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os
import time
import psutil
from collections import defaultdict
import seaborn as sns
import optuna
from concurrent.futures import ThreadPoolExecutor
# Especiales de RecSys
import surprise
from surprise import accuracy
from surprise import SVD
from surprise import SVDpp
from surprise.model_selection import PredefinedKFold
from surprise.model_selection import cross_validate
import implicit
import scipy.sparse as sparse

### Funciones utiles

In [ ]:
def costo_computacional(algoritmo, trainset, imprimir=True):
    proceso = psutil.Process()
    inicio_tiempo = time.time()
    inicio_cpu = proceso.cpu_percent(interval=None)
    inicio_memoria = proceso.memory_info().rss

    algoritmo.fit(trainset)

    fin_tiempo = time.time()
    fin_cpu = proceso.cpu_percent(interval=None)
    fin_memoria = proceso.memory_info().rss

    tiempo = fin_tiempo - inicio_tiempo
    cpu = fin_cpu - inicio_cpu
    memoria = (fin_memoria - inicio_memoria) / (1024 * 1024)

    if imprimir:
        print(f"Tiempo entrenamiento: {tiempo:.2f} segundos")
        print(f"Uso de CPU: {cpu:.2f}%")
        print(f"Uso de memoria: {memoria:.2f} MB")
    return tiempo, cpu, memoria

def get_top_n(predictions, n=10):
    """Devuelve las N-mejores recomendaciones para cada usuario de un set de predicción.

    Args:
        predictions(lista de objetos Prediction): La lista de predicción obtenida del método test.
        n(int): El número de recomendaciónes por usuario

    Returns:
    Un diccionario donde las llaves son ids de usuario y los valores son listas de tuplas:
        [(item id, rating estimation), ...] de tamaño n.
    """

    # First map the predictions to each user.
    top_n = defaultdict(list)
    for uid, iid, true_r, est, _ in predictions:
        top_n[uid].append((iid, est))

    # Then sort the predictions for each user and retrieve the k highest ones.
    for uid, user_ratings in top_n.items():
        user_ratings.sort(key=lambda x: x[1], reverse=True)
        top_n[uid] = user_ratings[:n]

    return top_n

# Definicion de métricas (No editar)

def precision_at_k(r, k):
    assert 1 <= k <= r.size
    return (np.asarray(r)[:k]).mean()

def average_precision_at_k(r, k):
    r = np.asarray(r)
    n_rel = r.sum() # Número de items relevantes
    if n_rel == 0:
        return 0.
    vectorized_precision = np.vectorize(lambda i: precision_at_k(r, i))
    indices = np.arange(1, len(r) + 1)
    precisions = vectorized_precision(indices) # Precision@k por cada posición del ranking
    score = np.sum(precisions * r)
    return score / min(k, n_rel)

def dcg_at_k(r, k):
    r = np.asarray(r)[:k]
    if r.size:
        return np.sum(np.subtract(np.power(2, r), 1) / np.log2(np.arange(2, r.size + 2)))
    return 0.

def ndcg_at_k(r, k):
    idcg = dcg_at_k(sorted(r, reverse=True), k)

    if not idcg:
        return 0.
    return dcg_at_k(r, k) / idcg

### Datos a utilizar

In [3]:
train_data = pd.read_csv("datos/train.csv")
validation_data = pd.read_csv("datos/validation.csv")
vg_data = pd.read_csv("datos/videogames_metadata.csv")

cantidad_items_distintos_original = validation_data["item_id"].nunique()
cantidad_reviews_validation_original = len(validation_data)
print(f"Reviews en el conjunto de validación: {cantidad_reviews_validation_original} sobre {cantidad_items_distintos_original} items únicos")
# Filtrar test_data para que solo contenga items presentes en train_data
validation_data = validation_data[validation_data["item_id"].isin(set(train_data["item_id"].unique()))].copy()
cantidad_items_distintos_modificado = validation_data["item_id"].nunique()
cantidad_reviews_validation_modificado = len(validation_data)
print(f"Reviews en el conjunto de validación: {cantidad_reviews_validation_modificado} ({cantidad_reviews_validation_modificado / cantidad_reviews_validation_original:.2%}) sobre {cantidad_items_distintos_modificado} ({cantidad_items_distintos_modificado / cantidad_items_distintos_original:.2%}) items únicos, presentes en train")

Reviews en el conjunto de validación: 22861 sobre 9246 items únicos
Reviews en el conjunto de validación: 20197 (88.35%) sobre 6849 (74.08%) items únicos, presentes en train

In [4]:
display(train_data.head(1))
display(validation_data.head(1))
display(vg_data.head(1))

,rating,review_title,text,user_id,timestamp,item_title,item_id
0,5.0,One of my favorites !,Great game in the series !,149157,2017-11-13 10:53:02.745,Medal of Honor - PC,4946

,rating,review_title,text,timestamp,item_title,item_id,user_id
0,5.0,Five Stars,yay,2015-03-16 16:15:22.000,WWF Smackdown 2: Know Your Role,23386,238159

,title,average_rating,rating_number,features,description,price,store,categories,item_id,image
0,Dash 8-300 Professional Add-On,5.0,1,"""Features Dash 8-300 and 8-Q300 (Q rollout liv...",The Dash 8-300 Professional Add-On lets you pi...,NaN,Aerosoft,"PC, Games",118568,https://m.media-amazon.com/images/I/21DVWE41A0...

### Necesario para Random, Uknn, Iknn y FunkSVD

In [5]:
# La lectura de datos sirve tanto para item-based como para funkSVD al usar Surprise
reader = surprise.Reader(rating_scale=(1,5))
trainset = surprise.Dataset.load_from_df(train_data[["user_id", "item_id", "rating"]], reader).build_full_trainset()
a_testset = trainset.build_anti_testset()
testset = a_testset 
# Este test set tiene 97,875,651 lo cual es demasiado grande para evaluar
# Por lo mismo lo vamos a reducir a solo los items rankeados por los vecinos de cada usuario
# Tal vez nisiquiera lo utilice directamente

In [6]:
# Diccionario de items jugados por cada usuario
user_items = {}
itemset = set()

for row in train_data.itertuples():
    if row[4] not in user_items:
        user_items[row[4]] = []

    user_items[row[4]].append(row[7])
    itemset.add(row[7])

### 1. Random

In [8]:
# Creamos un database de predicciones aleatorias que puede ser utilizado por get_top_n
random_pred = pd.DataFrame(testset, columns=['user_id', 'item_id', 'rating']) # Todas las combinaciones posibles
top_10 = (
    random_pred
    .groupby("user_id", group_keys=False)
    .apply(lambda x: x.sample(n=10, replace=False))
)
top_10 = top_10.reset_index(drop=True)

top_10_dict = defaultdict(list)
for user, group in top_10.groupby('user_id'):
    top_10_dict[user] = list(zip(group['item_id']))

/var/folders/ws/h3j5xbbs1s72dytc70rd22000000gn/T/ipykernel_1888/430861332.py:6: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.sample(n=10, replace=False))

### 2. User-based collaborative filtering

In [9]:
# Parte especifica de entrenamiento del algoritmo
myUserKnn = surprise.KNNBasic(k=7, sim_options={'name': 'pearson', 'user_based': True})
tiempo, cpu, memoria =costo_computacional(myUserKnn, trainset, True)

Computing the pearson similarity matrix...
Done computing similarity matrix.
Tiempo entrenamiento: 0.38 segundos
Uso de CPU: 95.30%
Uso de memoria: -10.39 MB

In [10]:
# Se genera un antitestset especial para user-based KNN debido a que el normal tiene mas de 90 millones de tuplas, pasando a 500k
testset_uknn = []
# Se obtienen los vecinos de cada usuario
for user_raw_id in user_items.keys():
    vecinos = myUserKnn.get_neighbors(trainset.to_inner_uid(user_raw_id), k=7)
    recomendables = set()
    for vecino in vecinos:
        vecino_raw_id = trainset.to_raw_uid(vecino)
        jugadas_por_vecino = user_items[vecino_raw_id]
        recomendables.update(jugadas_por_vecino)
    # Remover items ya jugados por el usuario
    recomendables.difference_update(set(user_items[user_raw_id]))
    for item in recomendables:
        testset_uknn.append((user_raw_id, item, 0)) # 0 es un rating que no sirve pero cumple el formato

In [11]:
# Se realizan las predicciones y se obtiene el top 10
predictions_uknn = myUserKnn.test(testset_uknn)
# Obtener las mejores N recomendaciones
top_n_uknn = get_top_n(predictions_uknn, n=10)

### 2. Item-based collaborative filtering

In [12]:
# Parte especifica de entrenamiento del algoritmo
myItemKnn = surprise.KNNBasic(k=7, sim_options={'name': 'pearson', 'user_based': False})
tiempo, cpu, memoria =costo_computacional(myItemKnn, trainset, False)

Computing the pearson similarity matrix...
Done computing similarity matrix.

In [13]:
# Se genera un antitestset especial para item-based KNN debido a que el normal tiene mas de 90 millones de tuplas, pasando a 180k
testset_iknn = []

# Primero se encuentran los vecinos de cada item
vecinos_items_dict = {}
for item in itemset:
    vecinos_items = myItemKnn.get_neighbors(trainset.to_inner_iid(item), k=7)
    vecinos_items_raw = []
    for vecino in vecinos_items:
        vecino_raw_id = trainset.to_raw_iid(vecino)
        vecinos_items_raw.append(vecino_raw_id)
    vecinos_items_dict[item] = set(vecinos_items_raw)

# Se itera por cada usuario
for user_raw_id in user_items.keys():
    recomendables = set()
    for item_raw_id in user_items[user_raw_id]:
        vecinos_items = vecinos_items_dict[item_raw_id]
        recomendables.update(vecinos_items)    
    # Remover items ya jugados por el usuario
    recomendables.difference_update(set(user_items[user_raw_id]))
    for item in recomendables:
        testset_iknn.append((user_raw_id, item, 0)) # 0 es un rating que no sirve pero cumple el formato

In [14]:
# Se realizan las predicciones y se obtiene el top 10
predictions_iknn = myItemKnn.test(testset_iknn)
# Obtener las mejores N recomendaciones
top_n_iknn = get_top_n(predictions_iknn, n=10)

### 3. FunkSVD

In [15]:
# Se genera el testest funk
testset_funk = testset_uknn.copy()
testset_funk.extend(testset_iknn)
testset_funk = list(set(testset_funk))

# Parte especifica de entrenamiento del algoritmo
funksvd = SVD(n_factors = 100, n_epochs = 20, lr_all = 0.005, reg_all = 0.02)
tiempo, cpu, memoria =costo_computacional(funksvd, trainset, imprimir = True)
predictions_funksvd = funksvd.test(testset_funk)

# Obtener las mejores N recomendaciones
top_n_funksvd = get_top_n(predictions_funksvd, n=10)

Tiempo entrenamiento: 0.48 segundos
Uso de CPU: 99.80%
Uso de memoria: -224.28 MB

### Preprocesamiento de los datos a formato sparse y funciones para ALS y BPR

In [16]:
df_test = validation_data[["user_id", "item_id", "rating", "timestamp"]].copy()

# rating >= 3 es relevante (1) y rating menor a 3 es no relevante (0)
df_test.rating = [1 if x >=3 else 0 for x in df_test.rating ]

df_test.sort_values(by=["user_id", "timestamp"], inplace=True)

user_items_test = {}

for row in df_test.itertuples():
    if row[1] not in user_items_test:
        user_items_test[row[1]] = []

    user_items_test[row[1]].append(row[2])

In [17]:
df_train = train_data[["user_id", "item_id"]].copy()

user_items = {}
itemset = set()

for row in df_train.itertuples():
    if row[1] not in user_items:
        user_items[row[1]] = []

    user_items[row[1]].append(row[2])
    itemset.add(row[2])

itemset = np.sort(list(itemset))

sparse_matrix = np.zeros((len(user_items), len(itemset)))

for i, items in enumerate(user_items.values()):
    sparse_matrix[i] = np.isin(itemset, items, assume_unique=True).astype(int)

matrix = sparse.csr_matrix(sparse_matrix.T)

user_ids = {key: i for i, key in enumerate(user_items.keys())}
user_item_matrix = matrix.T.tocsr()

# Para traducir los id back and forth
# Forward mappings: original ID → matrix index
user2id = {user: i for i, user in enumerate(user_items.keys())}
item2id = {item: i for i, item in enumerate(itemset)}

# Reverse mappings: matrix index → original ID
id2user = {i: user for user, i in user2id.items()}
id2item = {i: item for item, i in item2id.items()}

In [18]:
# Funciones
def evaluate_model(model, n):
  mean_ap = 0. # o MAP
  mean_ndcg = 0.
  for u in user_items_test.keys():
    u_original = u
    u_matriz = user2id[u]
    rec = model.recommend(u_matriz, user_item_matrix[u_matriz], n)[0]
    rec_original = [id2item[i] for i in rec]
    rel_vector = np.isin(rec_original, user_items_test[u_original], assume_unique=True).astype(int)
    mean_ap += average_precision_at_k(rel_vector, n)
    mean_ndcg += ndcg_at_k(rel_vector, n)

  mean_ap /= len(user_items_test)
  mean_ndcg /= len(user_items_test)

  return mean_ap, mean_ndcg

def show_recommendations(model, user, n):
  user_matriz = user2id[user]
  recommendations = model.recommend(userid=user_matriz, user_items=user_item_matrix[user_matriz], N=n)[0]
  recommendations_original = [id2item[i] for i in recommendations]
  return vg_data.loc[recommendations_original]['title']

def show_similar_movies(model, item, n=10):
  item_matriz = item2id[item]
  sim_items = model.similar_items(item_matriz, n)[0]
  sim_items_original = [id2item[i] for i in sim_items]
  return vg_data.loc[sim_items_original]['title']

### 4. ALS

In [19]:
factors = 117
iterations = 14
model_als = implicit.als.AlternatingLeastSquares(factors=factors, iterations=iterations, use_gpu=False)
tiempo, cpu, memoria =costo_computacional(model_als, user_item_matrix, imprimir = True)
# show_recommendations(model_als, user=59, n=10)
# show_similar_movies(model_als, item=171, n=10)
maprec, ndcg = evaluate_model(model_als, n=10)
print('map: {}\nndcg: {}'.format(maprec, ndcg))

# Best is trial 5 with value: 0.056847841963295974. {'factors': 117, 'iterations': 14}

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/implicit/cpu/als.py:95: RuntimeWarning: OpenBLAS is configured to use 10 threads. It is highly recommended to disable its internal threadpool by setting the environment variable 'OPENBLAS_NUM_THREADS=1' or by calling 'threadpoolctl.threadpool_limits(1, "blas")'. Having OpenBLAS use a threadpool can lead to severe performance issues here.
  check_blas_config()

  0%|          | 0/14 [00:00<?, ?it/s]

Tiempo entrenamiento: 3.22 segundos
Uso de CPU: 605.90%
Uso de memoria: -77.92 MB
map: 0.056907227354195684
ndcg: 0.07675716256508061

### 5. BPR

In [20]:
factors = 67
iterations = 300
model_bpr = implicit.bpr.BayesianPersonalizedRanking(factors=factors, iterations=iterations, use_gpu=False)
tiempo, cpu, memoria =costo_computacional(model_bpr, user_item_matrix, imprimir = True)
# show_recommendations(model_bpr, user=77, n=10)
# show_similar_movies(model_bpr, item=171, n=10)
maprec, ndcg = evaluate_model(model_bpr, n=10)
print('map: {}\nndcg: {}'.format(maprec, ndcg))

  0%|          | 0/300 [00:00<?, ?it/s]

Tiempo entrenamiento: 4.65 segundos
Uso de CPU: 143.90%
Uso de memoria: -134.03 MB
map: 0.03951116923996518
ndcg: 0.056074100707097625

### 6. Factorization Machines (bonus)

### Analisís sensibilidad usando optuna

In [ ]:
def objective(trial):
    factors = trial.suggest_int("factors", 50, 300)
    iterations = trial.suggest_int("iterations", 10, 40)
    model = implicit.als.AlternatingLeastSquares(factors=factors, iterations=iterations)
    model.fit(user_item_matrix)
    map_val, ndcg_val = evaluate_model(model, n=10)
    return map_val  # maximize MAP

study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=50)
print(study.best_params)

### Definicion metricas, por mientras esta aca

In [ ]:
# Calculo diversidad
dict_categorias_juegos = {}

for row in vg_data.itertuples():
    dict_categorias_juegos[row[9]] = []
    if type(row[8]) == str:
        for categoria in row[8].split(','):
            dict_categorias_juegos[row[9]].append(categoria.strip())

def diversidad_lista(recomendaciones: list, dict_categorias_juegos = dict_categorias_juegos):
    set_original = set()
    categorias = []
    totales = 0
    for item in recomendaciones:
        categorias.append(set(dict_categorias_juegos[item]))
        set_original.update(dict_categorias_juegos[item])
        totales += len(dict_categorias_juegos[item])
    
    diferentes = set(frozenset(s) for s in categorias)
    return len(diferentes)
    # return len(set_original)/totales

def recorrer_recomendaciones(top_recomendaciones, dict_categorias_juegos = dict_categorias_juegos):
    # Todas las metricas a calcular de las recomendaciones
    metrica_diversidad = []
    
    # Se recorre la lista por cada usuario y lo que se le recomendo
    for user, recomendaciones in top_recomendaciones.items():
        recoms = []
        for tupla in recomendaciones:
            recoms.append(tupla[0])
        # Metrica diversidad
        metrica_diversidad.append(diversidad_lista(recoms))

    
    # Calculate average diversity across all users
    metrica_diversidad = sum(metrica_diversidad) / len(metrica_diversidad) if metrica_diversidad else 0    
    return metrica_diversidad

In [ ]:
# Calculo novedad
frecuencia_items_train = train_data['item_id'].value_counts(normalize=True)
frecuencia_items_train.to_dict()

def novedad(top_recomendaciones, frecuencia_items_train=frecuencia_items_train):
    sumatoria_de_usuarios = 0
    u_cantidad_usuarios = len(top_recomendaciones) # variable U formula
    for user, recomendaciones in top_recomendaciones.items():
        l_cantidad_rec_usuario = len(recomendaciones) # variable L formula
        sumatoria_del_log = 0
        for tupla in recomendaciones:
            item_id = tupla[0]
            sumatoria_del_log += (np.log(1/frecuencia_items_train[item_id])) if item_id in frecuencia_items_train else 0
        sumatoria_del_log /= l_cantidad_rec_usuario
        sumatoria_de_usuarios += sumatoria_del_log
    
    return sumatoria_de_usuarios / u_cantidad_usuarios if u_cantidad_usuarios else 0

In [119]:
for nombre, rankings in [("random", top_10_dict), ("uknn", top_n_uknn), ("iknn", top_n_iknn), ("funk_svd", top_n_funksvd)]:
    diversidad_val = recorrer_recomendaciones(rankings)
    novedad_val = novedad(rankings)
    print(f"{nombre} - Diversidad: {diversidad_val}, Novedad: {novedad_val}")

random - Diversidad: 8.451324389404885, Novedad: 10.372988334630175
uknn - Diversidad: 9.046783625730994, Novedad: 8.85354341587188
iknn - Diversidad: 7.490884072927416, Novedad: 7.918964258424243
funk_svd - Diversidad: 8.207086343309253, Novedad: 7.598538964892776